version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: CaramelLabs-PostGres-01
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: Caramellabs_db_dev
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: CaramelLabs-Redis-01
    restart: always
    ports:
      - "6380:6379"